@host=https://localhost
@port=7280

### GET post
GET {{host}}:{{port}}/posts/1

### List posts
GET {{host}}:{{port}}/posts?page=1

### Create user
POST {{host}}:{{port}}/users
Content-Type: application/json

{
  "EmailAddress": "example@mail.com",
  "Name": "example",
  "Password": "Password1!"
}

### Update user
PUT {{host}}:{{port}}/users/1
Content-Type: application/json

{
  "EmailAddress": "new-example@mail.com",
  "Name": "new-example",
  "CurrentPassword": "Password1!",
  "NewPassword": "Password2?"
}

### Delete user
DELETE {{host}}:{{port}}/users/1

### Get user
GET {{host}}:{{port}}/users/1

### List users
GET {{host}}:{{port}}/users?page=1

### Sign in
POST {{host}}:{{port}}/users/sign-in
Content-Type: application/json

{
  "EmailAddress": "example@mail.com",
  "Password": "Password1!"
}

### Sign out
GET {{host}}:{{port}}/users/sign-out

### Create like
POST {{host}}:{{port}}/likes
Content-Type: application/json

{
  "PostId": 1
}

### Delete like
DELETE {{host}}:{{port}}/likes
Content-Type: application/json

{
  "PostId": 1
}
