@host=https://localhost
@port=7280

### Create user
POST {{host}}:{{port}}/users
Content-Type: application/json

{
  "EmailAddress": "example2@mail.com",
  "Name": "example2",
  "Password": "Password1!"
}

### Update user
PUT {{host}}:{{port}}/users/1
Content-Type: application/json

{
  "EmailAddress": "new-example@mail.com",
  "Name": "new-example",
  "CurrentPassword": "Password1!",
  "NewPassword": "Password2?"
}

### Delete user
DELETE {{host}}:{{port}}/users/1

### Get user
GET {{host}}:{{port}}/users/1

### Get user like stats
GET {{host}}:{{port}}/users/1/like-stats

### List users
GET {{host}}:{{port}}/users?page=1

### Sign in
POST {{host}}:{{port}}/users/sign-in
Content-Type: application/json

{
  "EmailAddress": "example@mail.com",
  "Password": "Password123!"
}

### Sign out
POST {{host}}:{{port}}/users/sign-out

### GET post
GET {{host}}:{{port}}/posts/2

### List posts
GET {{host}}:{{port}}/posts?page=1&sort_by=likes_count

### Create post
POST {{host}}:{{port}}/posts
Content-Type: application/json

{
  "Content": "Test"
}

### Update post
PUT {{host}}:{{port}}/posts/3
Content-Type: application/json

{
  "PostContent": "new content"
}

### Delete post
DELETE {{host}}:{{port}}/posts/3

### Create like
POST {{host}}:{{port}}/likes
Content-Type: application/json

{
  "PostId": 2
}

### Delete like
DELETE {{host}}:{{port}}/likes
Content-Type: application/json

{
  "PostId": 2
}
